/* Auto-generated by tools/gen_bgm_data.py - do not edit. */
#pragma once

#include <stddef.h>
#include <stdint.h>

/* Country Shop - 120,832 bytes ADPCM @ 8000Hz, block_align=1024 */
extern const unsigned char dex_bgm_country_shop[];

/* Library & Museum - 120,832 bytes ADPCM @ 8000Hz, block_align=1024 */
extern const unsigned char dex_bgm_library_museum[];

typedef struct {
    const char *name;
    const unsigned char *data;
    size_t len;
    uint16_t sample_rate;
    uint16_t block_align;
} dex_bgm_track_t;

extern const dex_bgm_track_t dex_bgm_tracks[];
extern const int dex_bgm_track_count;

#define DEX_BGM_TRACK_COUNT 2
