"""
Generate C source/header from ADPCM WAV files for firmware embedding.
Output: main/dex_bgm_data.c + main/dex_bgm_data.h
"""
import os, glob, struct

BGM_DIR = r"D:\Project\ai-passport-stardew-valley\tools\_bgm"
OUT_C = r"D:\Project\ai-passport-stardew-valley\main\dex_bgm_data.c"
OUT_H = r"D:\Project\ai-passport-stardew-valley\main\dex_bgm_data.h"

TRACKS = [
    ("stardew_overture", "Stardew Overture"),
    ("cloud_country",   "Cloud Country"),
]

def read_adpcm_wav(path):
    """Read IMA ADPCM WAV, return (sample_rate, block_align, adpcm_data_bytes)."""
    with open(path, "rb") as f:
        data = f.read()
    assert data[:4] == b"RIFF" and data[8:12] == b"WAVE"
    pos = 12
    sample_rate = 0
    block_align = 0
    adpcm_data = None
    while pos < len(data) - 8:
        chunk_id = data[pos:pos+4]
        chunk_size = struct.unpack("<I", data[pos+4:pos+8])[0]
        if chunk_id == b"fmt ":
            fmt = data[pos+8:pos+8+chunk_size]
            sample_rate = struct.unpack("<I", fmt[4:8])[0]
            block_align = struct.unpack("<H", fmt[12:14])[0]
        elif chunk_id == b"data":
            adpcm_data = data[pos+8:pos+8+chunk_size]
        pos += 8 + chunk_size
        if chunk_size & 1:
            pos += 1
    assert adpcm_data and block_align > 0
    return sample_rate, block_align, adpcm_data

# Generate C source
lines = []
lines.append("/* Auto-generated by tools/gen_bgm_data.py - do not edit. */")
lines.append('#include "dex_bgm_data.h"')
lines.append("")

track_info = []
for file_prefix, label in TRACKS:
    matches = glob.glob(os.path.join(BGM_DIR, f"{file_prefix}.wav"))
    if not matches:
        print(f"NOT FOUND: {file_prefix}.wav")
        continue
    sr, ba, adpcm = read_adpcm_wav(matches[0])
    sym = file_prefix
    track_info.append((sym, label, len(adpcm), sr, ba))
    
    lines.append(f"/* {label}: {len(adpcm):,} bytes ADPCM @ {sr}Hz, block_align={ba} */")
    lines.append(f"const unsigned char dex_bgm_{sym}[] = {{")
    for i in range(0, len(adpcm), 16):
        chunk = adpcm[i:i+16]
        hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_str},")
    lines.append("};")
    lines.append("")

# Define the tracks array in .c file where sizeof works
lines.append("const dex_bgm_track_t dex_bgm_tracks[] = {")
for sym, label, size, sr, ba in track_info:
    lines.append(f'    {{ "{label}", dex_bgm_{sym}, sizeof(dex_bgm_{sym}), {sr}, {ba} }},')
lines.append("};")
lines.append("")
lines.append(f"const int dex_bgm_track_count = {len(track_info)};")
lines.append("")

# Generate header
hlines = []
hlines.append("/* Auto-generated by tools/gen_bgm_data.py - do not edit. */")
hlines.append("#pragma once")
hlines.append("")
hlines.append("#include <stddef.h>")
hlines.append("#include <stdint.h>")
hlines.append("")

for sym, label, size, sr, ba in track_info:
    hlines.append(f"/* {label} - {size:,} bytes ADPCM @ {sr}Hz, block_align={ba} */")
    hlines.append(f"extern const unsigned char dex_bgm_{sym}[];")
    hlines.append("")

hlines.append("typedef struct {")
hlines.append("    const char *name;")
hlines.append("    const unsigned char *data;")
hlines.append("    size_t len;")
hlines.append("    uint16_t sample_rate;")
hlines.append("    uint16_t block_align;")
hlines.append("} dex_bgm_track_t;")
hlines.append("")
hlines.append("extern const dex_bgm_track_t dex_bgm_tracks[];")
hlines.append("extern const int dex_bgm_track_count;")
hlines.append("")
hlines.append(f"#define DEX_BGM_TRACK_COUNT {len(track_info)}")
hlines.append("")

with open(OUT_C, "w") as f:
    f.write("\n".join(lines))
with open(OUT_H, "w") as f:
    f.write("\n".join(hlines))

print(f"Generated: {OUT_C} ({os.path.getsize(OUT_C):,} bytes)")
print(f"Generated: {OUT_H} ({os.path.getsize(OUT_H):,} bytes)")
for i, (sym, label, size, sr, ba) in enumerate(track_info):
    print(f"  [{i}] {label}: {size:,} bytes @ {sr}Hz, block_align={ba}")
